name: 'Github Repo Reports'
description: 'Repository reports for Slack'
author: Param P <parama4u@gmail.com>
branding:
  icon: 'award'
  color: 'orange'
inputs:
  SLACK_WEBHOOK:  
    description: 'Link for the Slack webhook'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SLACK_WEBHOOK }}